#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aiboy'
require 'optparse'

options = {
  protocol: :binary,
  host: nil,
  port: nil,
  visible: false
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} ROM_PATH [options]"
  opts.separator ''
  opts.separator 'By default starts the fast binary-protocol server on port 9877.'
  opts.separator 'Use --protocol http for a human-friendly HTTP/JSON interface on port 9876.'
  opts.separator ''
  opts.on('--protocol PROTO', %i[binary http], 'binary (default) or http') { |v| options[:protocol] = v }
  opts.on('-p', '--port PORT', Integer, 'Port (default depends on protocol)') { |v| options[:port] = v }
  opts.on('-b', '--bind HOST', String, 'Bind address (default: 127.0.0.1)') { |v| options[:host] = v }
  opts.on('--visible', 'Open an SDL window alongside the server (default: headless)') { options[:visible] = true }
  opts.on('-h', '--help', 'Show this help') do
    puts opts
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => e
  warn e.message
  warn parser
  exit 1
end

rom_path = ARGV.shift
unless rom_path
  warn 'ROM_PATH is required'
  warn parser
  exit 1
end

emulator_class = options[:visible] ? Aiboy::Emulator : Aiboy::EmulatorHeadless
emulator = emulator_class.new(rom_path)

server_class = options[:protocol] == :http ? Aiboy::HttpServer : Aiboy::BinaryServer
host = options[:host] || server_class::DEFAULT_HOST
port = options[:port] || server_class::DEFAULT_PORT
server_class.new(emulator, host: host, port: port).start
